#!/usr/bin/env python3
import smtplib, argparse, sys, os, socket, configparser
from email.mime.text import MIMEText

def main(args):
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.ehlo()
        body = MIMEText(args.msg)
        body['Subject'] = args.subject
        body['To'] = args.to
        body['From'] = args.frm
        server.sendmail(from_addr=args.frm, to_addrs=args.to, msg=body.as_string())
    except Exception as e:
        # Print any error messages to stdout
        print(e)
    finally:
        server.quit()


if __name__ == "__main__":
    config = configparser.ConfigParser()
    if os.path.exists(os.path.expanduser('~')+'/.mailrc'):
        try:
            config.read(os.path.expanduser('~')+'/.mailrc')
        except:
            print('Error reading ~/.mailrc file.')

    SMTP_SERVER = config.get('DEFAULT', 'SMTP_SERVER', fallback='127.0.0.1')
    SMTP_PORT = config.get('DEFAULT', 'SMTP_PORT', fallback='25')
    SENDER = config.get('DEFAULT', 'SENDER', fallback = os.getlogin()+'@'+'.'.join(socket.getfqdn().split('.')[-2:]))

    
    parser = argparse.ArgumentParser(
        prog="mail", description="Send plain text email")
    parser.add_argument('--frm', '-f', help="Define from address (sender)", default=SENDER)
    parser.add_argument('--to', '-t', help="Define to address (receipient)")
    parser.add_argument('--subject', '-s', help="Define subject")
    parser.add_argument('--msg', '-m', help="Define message, user input should end with `Ctrd + d` or send it through pipe.", default=None)

    try:
       args = parser.parse_args(args=None if sys.argv[1:] else ['--help'])
       if not args.msg:
        args.msg=sys.stdin.read()
    except:
       sys.exit(0)

    main(args)
